### ISSUE TITLE
Max Date ignored in some cases

### ISSUE THREAD

**Issue by panagiwtisst** [tanvir0604/vue-dropdown-datepicker#14]
You seem to ignore the maxDate days value when you loop the first 9 days. 
`      // Days 1-9
      for (var i = start1; i <= end1; i++) {
          if (this.daySuffixes) {
              day = i + this.getSuffix(i);
          } else {
              day = '0' + i;
          }
          this.days.push(i);
          this.dayOptions.push(day);
      }`
This block causes the issue. The `end1` value should be updated before looping this.
I added a PR to solve it

**Comment by tanvir0604** [comment]
Thanks for identify and PR
