### ISSUE TITLE
Does v-model work with the component? if not, is there an on change for all dropdowns or do I need to set them all?

### ISSUE THREAD

**Issue by techsev** [tanvir0604/vue-dropdown-datepicker#2]
The component loads fine but my changes aren't being assigned to the v-model variable, any ideas why?

<dropdown-datepicker v-model="current_selection" default-date-format="dd-mm-yyyy" v-bind:max-year="(new Date().getFullYear() + 1)" display-format="dmy" sort-year="asc" v-bind:allow-past="false" v-bind:required="true"></dropdown-datepicker>

**Comment by tanvir0604** [comment]
Did you use v-model to the associated input field?Can you please show your code sample?
There are on change event for every dropdown.Please check the documentation events section.

**Comment by tanvir0604** [comment]
Hi, is the problem solved?

**Comment by tanvir0604** [comment]
I am gonna close the issue,If you find any other problem then feel free to discuss
