### ISSUE TITLE
Month is not 2 digit format

### ISSUE THREAD

**Issue by oprogfrogo** [tanvir0604/vue-dropdown-datepicker#6]
Instead of
```
2022-09-01
```
I get:
```
2022-9-01
```

How can I force the month to be 2 digits? I am using the `onChange(day, month, year)` example you have in your docs

**Comment by tanvir0604** [comment]
Thanks for mentioning the issue.I have fixed it,can you please recheck and confirm if it works?Please use latest version mentioned in latest documentation.
Thanks

**Comment by tanvir0604** [comment]
@oprogfrogo can you please confirm the issue?If resolved then please close the issue.

**Comment by oprogfrogo** [comment]
Yes will check it soon. Sorry for the delay.

**Comment by oprogfrogo** [comment]
It's good now. Thanks!
